apiVersion: v1
kind: Service
metadata:
  name: search
  labels: 
    app: search
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 8080
    name: http
  externalIPs:
  - 192.168.0.171
  selector:  
    app: search
